name: flutter_tools
version: 0.0.38
description: Tools for building Flutter applications
homepage: http://flutter.io
author: Flutter Authors <flutter-dev@googlegroups.com>

environment:
  sdk: '>=1.19.0 <2.0.0'

dependencies:
  archive: ^1.0.20
  args: ^0.13.4
  coverage: ^0.8.0
  crypto: '>=1.1.1 <3.0.0'
  file: ^0.1.0
  http: ^0.11.3
  json_rpc_2: ^2.0.0

  # Version 1.0.4 has mysterious "pub get" spam about "drudge". If you update
  # this dependency, be sure not to include 1.0.4 and to check the output of
  # "pub get" for spam about "drudge".
  json_schema: 1.0.3

  linter: ^0.1.21
  meta: ^1.0.3
  mustache: ^0.2.5
  package_config: '>=0.1.5 <2.0.0'
  path: ^1.3.0
  pub_semver: ^1.0.0
  stack_trace: ^1.4.0
  usage: ^2.2.1
  web_socket_channel: ^1.0.4
  xml: ^2.4.1
  yaml: ^2.1.3

  # We depend on very specific internal implementation details of the
  # 'test' package, which change between versions, so here we pin it
  # precisely.
  test: 0.12.15+4

  # Version from the vended Dart SDK as defined in `dependency_overrides`.
  analyzer: any

dev_dependencies:
  mockito: ^1.0.0

# Exclude this package from the hosted API docs.
dartdoc:
  nodoc: true

dependency_overrides:
  analyzer:
    path: ../../bin/cache/dart-sdk/lib/analyzer
