sudo: false
addons:
  apt:
    # sky_shell binary depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
install:
  - gem install coveralls-lcov
  - npm install -g firebase-tools@">=3.0.4 <3.1.0"
before_script:
  - ./dev/bots/setup.sh
script:
  - ./dev/bots/test.sh
after_success:
  - (cd packages/flutter && coveralls-lcov coverage/lcov.info)
cache:
  directories:
    - $HOME/.pub-cache
