os:
  - linux
  - osx
sudo: false
filter_secrets: false
addons:
  apt:
    # sky_shell binary depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
language: node_js
node_js:
  - "6"
install:
  - ./dev/bots/travis_install.sh
env:
  - SHARD=analyze
  - SHARD=tests
  - SHARD=docs
before_script:
  - ./dev/bots/travis_setup.sh
script:
  - ulimit -S -n 2048 # https://github.com/flutter/flutter/issues/2976
  - (./bin/cache/dart-sdk/bin/dart ./dev/bots/test.dart && ./dev/bots/travis_upload.sh)
cache:
  directories:
    - $HOME/.pub-cache
matrix:
  exclude:
  - os: osx
    env: SHARD=analyze
  - os: osx
    env: SHARD=docs
