install:
- cmd: bin\flutter.bat config --no-analytics
- cmd: bin\flutter.bat update-packages

cache:
- '%APPDATA%\Pub\Cache'

build: off

test_script:
- cmd: bin\cache\dart-sdk\bin\dart.exe -c dev\bots\test.dart
