name: flutter_gallery
dependencies:
  flutter:
    sdk: flutter
  collection: 1.14.3
  intl: 0.15.2
  string_scanner: 1.0.2
  url_launcher: 0.4.2+5
  cupertino_icons: 0.1.1

  # Also update dev/benchmarks/complex_layout/pubspec.yaml
  flutter_gallery_assets:
    git:
      url: https://flutter.googlesource.com/gallery-assets
      ref: 6427f36af1bdb2fffaeda1c46d5e52d7b636c93d

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  args: 0.13.7 # TRANSITIVE DEPENDENCY
  async: 1.13.3 # TRANSITIVE DEPENDENCY
  barback: 0.15.2+13 # TRANSITIVE DEPENDENCY
  boolean_selector: 1.0.2 # TRANSITIVE DEPENDENCY
  charcode: 1.1.1 # TRANSITIVE DEPENDENCY
  convert: 2.0.1 # TRANSITIVE DEPENDENCY
  crypto: 2.0.2+1 # TRANSITIVE DEPENDENCY
  file: 2.3.4 # TRANSITIVE DEPENDENCY
  glob: 1.1.5 # TRANSITIVE DEPENDENCY
  http: 0.11.3+14 # TRANSITIVE DEPENDENCY
  http_multi_server: 2.0.4 # TRANSITIVE DEPENDENCY
  http_parser: 3.1.1 # TRANSITIVE DEPENDENCY
  io: 0.3.0 # TRANSITIVE DEPENDENCY
  js: 0.6.1 # TRANSITIVE DEPENDENCY
  json_rpc_2: 2.0.4 # TRANSITIVE DEPENDENCY
  matcher: 0.12.1+4 # TRANSITIVE DEPENDENCY
  meta: 1.1.1 # TRANSITIVE DEPENDENCY
  mime: 0.9.4 # TRANSITIVE DEPENDENCY
  mockito: 2.2.0 # TRANSITIVE DEPENDENCY
  node_preamble: 1.4.0 # TRANSITIVE DEPENDENCY
  package_config: 1.0.3 # TRANSITIVE DEPENDENCY
  package_resolver: 1.0.2 # TRANSITIVE DEPENDENCY
  path: 1.4.2 # TRANSITIVE DEPENDENCY
  pool: 1.3.3 # TRANSITIVE DEPENDENCY
  pub_semver: 1.3.2 # TRANSITIVE DEPENDENCY
  quiver: 0.26.0 # TRANSITIVE DEPENDENCY
  shelf: 0.7.1 # TRANSITIVE DEPENDENCY
  shelf_packages_handler: 1.0.3 # TRANSITIVE DEPENDENCY
  shelf_static: 0.2.6 # TRANSITIVE DEPENDENCY
  shelf_web_socket: 0.2.2 # TRANSITIVE DEPENDENCY
  source_map_stack_trace: 1.1.4 # TRANSITIVE DEPENDENCY
  source_maps: 0.10.4 # TRANSITIVE DEPENDENCY
  source_span: 1.4.0 # TRANSITIVE DEPENDENCY
  stack_trace: 1.9.0 # TRANSITIVE DEPENDENCY
  stream_channel: 1.6.2 # TRANSITIVE DEPENDENCY
  term_glyph: 1.0.0 # TRANSITIVE DEPENDENCY
  test: 0.12.26 # TRANSITIVE DEPENDENCY
  typed_data: 1.1.4 # TRANSITIVE DEPENDENCY
  vector_math: 2.0.5 # TRANSITIVE DEPENDENCY
  vm_service_client: 0.2.3 # TRANSITIVE DEPENDENCY
  web_socket_channel: 1.0.6 # TRANSITIVE DEPENDENCY
  yaml: 2.1.13 # TRANSITIVE DEPENDENCY

flutter:
  uses-material-design: true
  assets:
    - lib/gallery/example_code.dart
    - packages/flutter_gallery_assets/appbar_background.jpg
    - packages/flutter_gallery_assets/appbar/appbar_background_layer0.png
    - packages/flutter_gallery_assets/appbar/appbar_background_layer1.png
    - packages/flutter_gallery_assets/appbar/appbar_background_layer2.png
    - packages/flutter_gallery_assets/appbar/appbar_background_layer3.png
    - packages/flutter_gallery_assets/appbar/appbar_background_layer4.png
    - packages/flutter_gallery_assets/appbar/appbar_background_layer5.png
    - packages/flutter_gallery_assets/pesto/avatar.jpg
    - packages/flutter_gallery_assets/pesto/image10.jpg
    - packages/flutter_gallery_assets/pesto/image11.jpg
    - packages/flutter_gallery_assets/pesto/image12.jpg
    - packages/flutter_gallery_assets/pesto/image13.jpg
    - packages/flutter_gallery_assets/pesto/image1.jpg
    - packages/flutter_gallery_assets/pesto/image2.jpg
    - packages/flutter_gallery_assets/pesto/image3.jpg
    - packages/flutter_gallery_assets/pesto/image4.jpg
    - packages/flutter_gallery_assets/pesto/image5.jpg
    - packages/flutter_gallery_assets/pesto/image6.jpg
    - packages/flutter_gallery_assets/pesto/image7.jpg
    - packages/flutter_gallery_assets/pesto/image8.jpg
    - packages/flutter_gallery_assets/pesto/image9.jpg
    - packages/flutter_gallery_assets/pesto/logo_small.png
    - packages/flutter_gallery_assets/pesto/logo_medium.png
    - packages/flutter_gallery_assets/pesto/fish.png
    - packages/flutter_gallery_assets/pesto/healthy.png
    - packages/flutter_gallery_assets/pesto/main.png
    - packages/flutter_gallery_assets/pesto/meat.png
    - packages/flutter_gallery_assets/pesto/quick.png
    - packages/flutter_gallery_assets/pesto/spicy.png
    - packages/flutter_gallery_assets/pesto/veggie.png
    - packages/flutter_gallery_assets/about_logo.png
    - packages/flutter_gallery_assets/ali_connors.jpg
    - packages/flutter_gallery_assets/drawer_logo.png
    - packages/flutter_gallery_assets/kangaroo_valley_safari.jpg
    - packages/flutter_gallery_assets/top_10_australian_beaches.jpg
    - packages/flutter_gallery_assets/landscape_0.jpg
    - packages/flutter_gallery_assets/landscape_1.jpg
    - packages/flutter_gallery_assets/landscape_2.jpg
    - packages/flutter_gallery_assets/landscape_3.jpg
    - packages/flutter_gallery_assets/landscape_4.jpg
    - packages/flutter_gallery_assets/landscape_5.jpg
    - packages/flutter_gallery_assets/landscape_6.jpg
    - packages/flutter_gallery_assets/landscape_7.jpg
    - packages/flutter_gallery_assets/landscape_8.jpg
    - packages/flutter_gallery_assets/landscape_9.jpg
    - packages/flutter_gallery_assets/landscape_10.jpg
    - packages/flutter_gallery_assets/landscape_11.jpg
    - packages/flutter_gallery_assets/shrine/products/backpack.png
    - packages/flutter_gallery_assets/shrine/products/beachball.png
    - packages/flutter_gallery_assets/shrine/products/binoculars.png
    - packages/flutter_gallery_assets/shrine/products/brush.png
    - packages/flutter_gallery_assets/shrine/products/chair.png
    - packages/flutter_gallery_assets/shrine/products/chucks.png
    - packages/flutter_gallery_assets/shrine/products/clock.png
    - packages/flutter_gallery_assets/shrine/products/fish_bowl.png
    - packages/flutter_gallery_assets/shrine/products/flippers.png
    - packages/flutter_gallery_assets/shrine/products/green-shoes.png
    - packages/flutter_gallery_assets/shrine/products/heels.png
    - packages/flutter_gallery_assets/shrine/products/helmet.png
    - packages/flutter_gallery_assets/shrine/products/lawn_chair.png
    - packages/flutter_gallery_assets/shrine/products/lipstick.png
    - packages/flutter_gallery_assets/shrine/products/popsicle.png
    - packages/flutter_gallery_assets/shrine/products/radio.png
    - packages/flutter_gallery_assets/shrine/products/sunnies.png
    - packages/flutter_gallery_assets/shrine/products/surfboard.png
    - packages/flutter_gallery_assets/shrine/products/teapot.png
    - packages/flutter_gallery_assets/shrine/vendors/16c477b.jpg
    - packages/flutter_gallery_assets/shrine/vendors/ali-connors.png
    - packages/flutter_gallery_assets/shrine/vendors/peter-carlsson.png
    - packages/flutter_gallery_assets/shrine/vendors/sandra-adams.jpg
    - packages/flutter_gallery_assets/shrine/vendors/zach.jpg
    - packages/flutter_gallery_assets/cupertino_navigation/person1.jpg
    - packages/flutter_gallery_assets/cupertino_navigation/person2.jpg
  fonts:
    - family: Raleway
      fonts:
        - asset: packages/flutter_gallery_assets/pesto/fonts/Raleway-Regular.ttf
        - asset: packages/flutter_gallery_assets/pesto/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: packages/flutter_gallery_assets/pesto/fonts/Raleway-SemiBold.ttf
          weight: 600
    - family: AbrilFatface
      fonts:
        - asset: packages/flutter_gallery_assets/shrine/fonts/abrilfatface/AbrilFatface-Regular.ttf
