name: flutter_driver
version: 0.0.1
description: Integration and performance test API for Flutter applications
homepage: http://flutter.io
author: Flutter Authors <flutter-dev@googlegroups.com>

environment:
  sdk: '>=1.19.0 <2.0.0'

dependencies:
  file: '^0.1.0'
  json_rpc_2: '^2.0.0'
  matcher: '>=0.12.0 <1.0.0'
  path: '^1.3.0'
  web_socket_channel: '^1.0.0'
  vm_service_client: '^0.2.0'
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  test: 0.12.15+4
  mockito: ^1.0.0
  quiver: ^0.21.4
