name: flutter_devicelab
version: 0.0.1
author: Flutter Authors <flutter-dev@googlegroups.com>
description: Flutter continuous integration performance and correctness tests.
homepage: https://github.com/flutter/flutter

environment:
  sdk: '>=1.12.0 <2.0.0'

dependencies:
  args: 0.13.7
  file: 2.3.4
  image: 1.1.29
  meta: 1.1.1
  path: 1.4.2
  platform: 2.1.1
  process: 2.0.6
  stack_trace: 1.9.0
  vm_service_client: 0.2.3

dev_dependencies:
  # See packages/flutter_test/pubspec.yaml for why we're pinning this version.
  test: 0.12.26

  archive: 1.0.32 # TRANSITIVE DEPENDENCY
  async: 1.13.3 # TRANSITIVE DEPENDENCY
  barback: 0.15.2+13 # TRANSITIVE DEPENDENCY
  boolean_selector: 1.0.2 # TRANSITIVE DEPENDENCY
  browser: 0.10.0+2 # TRANSITIVE DEPENDENCY
  charcode: 1.1.1 # TRANSITIVE DEPENDENCY
  collection: 1.14.3 # TRANSITIVE DEPENDENCY
  convert: 2.0.1 # TRANSITIVE DEPENDENCY
  crypto: 2.0.2+1 # TRANSITIVE DEPENDENCY
  glob: 1.1.5 # TRANSITIVE DEPENDENCY
  http: 0.11.3+14 # TRANSITIVE DEPENDENCY
  http_multi_server: 2.0.4 # TRANSITIVE DEPENDENCY
  http_parser: 3.1.1 # TRANSITIVE DEPENDENCY
  intl: 0.15.2 # TRANSITIVE DEPENDENCY
  io: 0.3.0 # TRANSITIVE DEPENDENCY
  js: 0.6.1 # TRANSITIVE DEPENDENCY
  json_rpc_2: 2.0.4 # TRANSITIVE DEPENDENCY
  matcher: 0.12.1+4 # TRANSITIVE DEPENDENCY
  mime: 0.9.4 # TRANSITIVE DEPENDENCY
  node_preamble: 1.4.0 # TRANSITIVE DEPENDENCY
  package_config: 1.0.3 # TRANSITIVE DEPENDENCY
  package_resolver: 1.0.2 # TRANSITIVE DEPENDENCY
  petitparser: 1.6.1 # TRANSITIVE DEPENDENCY
  pool: 1.3.3 # TRANSITIVE DEPENDENCY
  pub_semver: 1.3.2 # TRANSITIVE DEPENDENCY
  shelf: 0.7.1 # TRANSITIVE DEPENDENCY
  shelf_packages_handler: 1.0.3 # TRANSITIVE DEPENDENCY
  shelf_static: 0.2.6 # TRANSITIVE DEPENDENCY
  shelf_web_socket: 0.2.2 # TRANSITIVE DEPENDENCY
  source_map_stack_trace: 1.1.4 # TRANSITIVE DEPENDENCY
  source_maps: 0.10.4 # TRANSITIVE DEPENDENCY
  source_span: 1.4.0 # TRANSITIVE DEPENDENCY
  stream_channel: 1.6.2 # TRANSITIVE DEPENDENCY
  string_scanner: 1.0.2 # TRANSITIVE DEPENDENCY
  term_glyph: 1.0.0 # TRANSITIVE DEPENDENCY
  typed_data: 1.1.4 # TRANSITIVE DEPENDENCY
  web_socket_channel: 1.0.6 # TRANSITIVE DEPENDENCY
  xml: 2.6.0 # TRANSITIVE DEPENDENCY
  yaml: 2.1.13 # TRANSITIVE DEPENDENCY
