name: complex_layout
description: A new flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  # Also examples/flutter_gallery/pubspec.yaml
  flutter_gallery_assets:
    git:
      url: https://flutter.googlesource.com/gallery-assets
      ref: ef928550119411358b8b25e16aecde6ace513526

dev_dependencies:
  flutter_test:
    sdk: flutter
