name: flutter_test
dependencies:
  quiver: ^0.21.4

  # The flutter tools depend on very specific internal implementation
  # details of the 'test' package, which change between versions, so
  # here we pin it precisely to avoid version skew across our packages.
  test: 0.12.15+4

  flutter:
    sdk: flutter
